spring:
  application:
    name: convertor

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      refresh:
        enable: false
server:
  port: 8080
logging:
  level:
    org.springframework.web: DEBUG
  

